Repository slackware64:         mongodb         unixODBC         adesklets         conky         gambas3         mkvtoolnix-gtk

diff --git a/slackware64/database/mongodb/src/mongodb.SlackBuild b/slackware64/database/mongodb/src/mongodb.SlackBuild
--- a/slackware64/database/mongodb/src/mongodb.SlackBuild
+++ b/slackware64/database/mongodb/src/mongodb.SlackBuild
@@ -1,11 +1,10 @@
 #!/bin/sh
  
 # Heavily based on the Slackware 14.0 SlackBuild
-# Written by Andrea Sciucca ( gohanz at infinito.it)
-# Last build from miklos < ardutu at gmail dot com >
-# 
-# Slackware build script for mkvtoolnix
-# Official Site: http://www.bunkus.org/videotools/mkvtoolnix/
+# Written by miklos < ardutu at gmail dot com >
+#
+# Slackware build script for mongodb
+# Official Site: http://www.mongodb.org/
 #
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -24,22 +23,21 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# Require: libmatroska wxGTK
+# Require:
 
 set -e
 
 # Basic information.
-PKGNAME=mkvtoolnix-gtk
-SRCNAME=mkvtoolnix
-VERSION=${VERSION:-6.0.0}
+PKGNAME=mongodb
+VERSION=${VERSION:-2.2.2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
 ARCH=${ARCH:-x86_64}
-SOURCE="http://www.bunkus.org/videotools/mkvtoolnix/sources/$SRCNAME-$VERSION.tar.xz"
+SOURCE="http://downloads.mongodb.org/src/${PKGNAME}-src-r${VERSION}.tar.gz"
 TAR=      # empty = auto
 DIR=      # empty = auto
-DOCS="AUTHORS COPYING ChangeLog INSTALL NEWS README TODO"
-SLKFILES="" # all files needed to the slackbuild (except slack-desc etc..)
+DOCS="APACHE-2.0.txt GNU-AGPL-3.0.txt README"
+SLKFILES="libdir.patch" # all files needed to the slackbuild (except slack-desc etc..)
 
 # An EULA for non-free packages
 if [ -e EULA.TXT ];then
@@ -81,6 +79,17 @@ elif [ "$ARCH" = "x86_64" ]; then
   CHOST="x86_64"
 fi
 
+if ! grep -q "^mongodb:" /etc/group; then
+  echo "Group mongodb not found!!! You must have this group in order to build package. Try the following command"
+  echo "groupadd mongodb &>/dev/null"
+  exit 1
+fi
+if ! grep -q "^mongodb:" /etc/passwd; then
+  echo "User mongodb not found!!! You must have this user in order to build package. Try the following command"
+  echo "useradd -d /var/lib/mongodb -s /bin/false -c \"Mongodb user\" -g mongodb mongodb &>/dev/null"
+  exit 1
+fi
+
 ### Preparing Source
 rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
@@ -91,21 +100,27 @@ cd $DIR
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
-# Customize as you need
-CFLAGS="$SLKCFLAGS" \
-CXXFLAGS="$SLKCFLAGS" \
-./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib$LIBDIRSUFFIX \
-  --sysconfdir=/etc \
-  --localstatedir=/var \
-  --mandir=/usr/man \
-  --enable-gui \
-  --enable-wxwidgets \
-  --with-boost \
-  --build=$CHOST-slackware-linux
-./drake pkgdatadir=/usr/doc/$PKGNAME-$VERSION
-./drake pkgdatadir=/usr/doc/$PKGNAME-$VERSION install DESTDIR=$PKG
+patch -p0 < $CWD/libdir.patch
+
+#build from source
+scons --use-system-boost=yes --use-system-pcre=yes --ssl=yes --sharedclient
+scons --prefix=$PKG/usr install 
+
+#copy man pages
+mkdir -p $PKG/usr/man/man1
+cp -a debian/*.1 $PKG/usr/man/man1
+
+#copy configuration file
+mkdir -p $PKG/etc/mongodb
+cat debian/mongodb.conf > $PKG/etc/mongodb/mongodb.conf.new
+
+#copy startup script
+mkdir -p $PKG/etc/rc.d
+cat $CWD/rc.mongod > $PKG/etc/rc.d/rc.mongod.new
+
+#make database dir
+mkdir -p $PKG/var/lib/mongodb $PKG/var/log/mongodb
+chown -R mongodb.mongodb $PKG/var/lib/mongodb $PKG/var/log/mongodb
 
 # Documentations
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
@@ -144,9 +159,6 @@ chown -R root:root $PKG
 if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
   requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
   [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
-  cat > install/slack-conflicts << EOF
-mkvtoolnix-qt
-EOF
 fi
 
 # Packaging
