Repository slackware:         midori

diff --git a/slackware/network/midori/midori.SlackBuild b/slackware/network/midori/midori.SlackBuild
--- a/slackware/network/midori/midori.SlackBuild
+++ b/slackware/network/midori/midori.SlackBuild
@@ -1,8 +1,10 @@
 #!/bin/sh
+ 
 # Heavily based on the Slackware 14.0 SlackBuild
-# http://software.twotoasts.de/?page=midori
-# Packager Michelino Chionchio - www.slacky.eu
-#
+# Written by miklos < ardutu at gmail dot com >
+# 
+# Slackware build script for midori
+# Official Site: http://software.twotoasts.de/?page=midori
 #
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -21,83 +23,110 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# Required:  webkitgtk, libunique, vala (Only Compilation)
-#
-# Exit on most errors
+# Require: libunique, webkitgtk, dconf
+
 set -e
 
-
-# Set variables:
-CWD=`pwd`
-OUTPUT=${OUTPUT:-$CWD}
+# Basic information.
 PKGNAME=midori
-TMP=${TMP:-/tmp/txz/$PKGNAME}
-PKG=$TMP/package
-VERSION=${VERSION:-0.4.7}
-ARCH=${ARCH:-i486}
-JOBS=${JOBS:--j2}
+VERSION=${VERSION:-0.5.2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
+ARCH=${ARCH:-i486}
+SOURCE="http://www.midori-browser.org/downloads/${PKGNAME}_${VERSION}_all_.tar.bz2"
+TAR=      # empty = auto
+DIR=$PKGNAME-$VERSION
+DOCS="AUTHORS COPYING ChangeLog EXPAT HACKING INSTALL README TODO TRANSLATE"
+SLKFILES="" # all files needed to the slackbuild (except slack-desc etc..)
 
-# Download sorce tarball if still not present
-SOURCE="http://archive.xfce.org/src/apps/midori/0.4/$PKGNAME-$VERSION.tar.bz2"
-
-if [ ! -e $CWD/$PKGNAME-$VERSION.tar.bz2 ]; then
- wget $SOURCE
+# An EULA for non-free packages
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])":
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
 fi
 
-
-# Set compiling FLAGS
+# Does not touch following if not needed
+JOBS=${JOBS:--j2}
+CWD=$(pwd)
+TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
+PKG=$TMP/package-$PKGNAME
+OUTPUT=${OUTPUT:-$CWD}
+TAR=${TAR:-$(basename $SOURCE)}
+DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
+ 
+if [ ! -e "$CWD/$TAR" ];then
+  wget "$SOURCE" -O "$CWD/$TAR"
+fi
+ 
+CHOST="i486"
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"; SLKLDFLAGS=""; LIBDIRSUFFIX=""; CHOST="i486"
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"; SLKLDFLAGS=""; LIBDIRSUFFIX=""; CHOST="i686"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"; SLKLDFLAGS="-L/usr/lib64"; LIBDIRSUFFIX="64"; CHOST="x86_64"
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+  CHOST="x86_64"
 fi
 
-
-# Create build directory
-rm -rf $PKG
+### Preparing Source
+rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
-
-
-# Decompress the source tarball
 cd $TMP
-tar xvjf $CWD/$PKGNAME-$VERSION.tar.bz2
-
-echo -e "\E[0;32m+-------------------------+\E[0;0m"
-echo -e "\E[0;32m| Start SlackBuild Midori |\E[0;0m"
-echo -e "\E[0;32m+-------------------------+\E[0;0m"
-
-# Adjust permissions and ownerships
-cd $PKGNAME-$VERSION
+tar xvf $CWD/$TAR
+cd $DIR
+ 
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
-export CCFLAGS="$SLKCFLAGS"
-export CXXFLAGS="$SLKCFLAGS"
-
-# Building Midori package
+# Customize as you need
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
 ./waf configure \
    --prefix=/usr \
    --libdir=/usr/lib$LIBDIRSUFFIX \
    --docdir=/usr/doc/$PKGNAME-$VERSION \
    --sysconfdir=/etc \
    --localstatedir=/var \
+   --disable-gtk3 \
+   --disable-zeitgeist \
    --enable-unique \
    --enable-addons
-echo -e "\E[0;32mPress any key to build the package!\E[0;0m"
-read
 ./waf build
 ./waf install --destdir=$PKG
-
 
 # Don't clobber existing configs
 mv $PKG/etc/xdg/midori/search $PKG/etc/xdg/midori/search.new
 mv $PKG/etc/xdg/midori/extensions/adblock/config $PKG/etc/xdg/midori/extensions/adblock/config.new
 
-# Strip binaries and shared objects, if present
+# Documentations
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
+ 
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
+cd $CWD
+for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT $SLKFILES;do
+  [ -e $SB ]&&cp -r $SB $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$SB
+done
+
+if [ -d $PKG/usr/man ]; then
+    ( cd $PKG/usr/man
+      find . -type f -exec gzip -9 {} \;
+      for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+    )
+fi
+
+# Strip binary files
 ( cd $PKG
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
@@ -105,36 +134,24 @@ mv $PKG/etc/xdg/midori/extensions/adblock/config $PKG/etc/xdg/midori/extensions/
 )
 
 
-#Add documentation files: readme, changelog and so on
-mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
-cp -a AUTHORS COPYING ChangeLog EXPAT HACKING INSTALL README TODO TRANSLATE \
-  $PKG/usr/doc/$PKGNAME-$VERSION
-chmod 644 $PKG/usr/doc/$PKGNAME-$VERSION/*
-
-
-
-# Also add the slack-desk file and this slackbuild to the package
+# Preparing to packaging
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/doinst.sh  > $PKG/install/doinst.sh
-cat $CWD/slack-desc > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-desc
-cat $CWD/$PKGNAME.SlackBuild > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$PKGNAME.SlackBuild
-
-
+[ -e $CWD/doinst.sh ] && cat $CWD/doinst.sh > $PKG/install/doinst.sh
+[ -e $CWD/doinst.sh.gz ] && zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
 cd $PKG
 chown -R root:root $PKG
-if [ -x /usr/bin/requiredbuilder ];then
-requiredbuilder -y -v -s  $CWD $PKG
+ 
+if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
+  ADD=$(ls /var/log/packages/ | sed -ne 's/\(dconf\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2/p') \
+  requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
+  [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
-# Create txz package
+
+# Packaging
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
-
-
-# Cleanup if enabled
+ 
 if [ "$1" = "--cleanup" ]; then
- rm -rf $TMP
+  rm -rf $TMP
 fi
-
-
-
