Repository slackware:         fcgi         libmicrohttpd         libnfs         nginx         flash-player-plugin

diff --git a/slackware/system/flash-player-plugin/flash-player-plugin.SlackBuild b/slackware/system/flash-player-plugin/flash-player-plugin.SlackBuild
--- a/slackware/system/flash-player-plugin/flash-player-plugin.SlackBuild
+++ b/slackware/system/flash-player-plugin/flash-player-plugin.SlackBuild
@@ -1,11 +1,12 @@
 #!/bin/sh
 
 # Heavily based on the Slackware 14.0 SlackBuild
-# Written by Loris Vincenzi (http://www.slacky.eu)
-# Last build from Loris Vincenzi (http://www.slacky.eu)
+
+# Written by Matteo Rossini ( zerouno @ slacky.it )
+# Last build from 6c33c ( seic33c [at] gmail [dot] com)
 
 # Slackware build script for flash-player-plugin
-# Official Site: http://www.adobe.com
+# Official Site: http://get.adobe.com/it/flashplayer/
 
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -23,101 +24,116 @@
 # WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-#
-#
-# Exit on most errors
+
 set -e
 
 
-# Set variables:
-CWD=`pwd`
-OUTPUT=${OUTPUT:-$CWD}
+# Basic information. 
 PKGNAME=flash-player-plugin
-TMP=${TMP:-/tmp/txz/$PKGNAME}
-PKG=$TMP/package
-VERSION=${VERSION:-11.2.202.238}
-ARCH=${ARCH:-i386} # i386 or x86_64
+VERSION=${VERSION:-11.2.202.280}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
+ARCH=${ARCH:-i386}
+SOURCE="http://fpdownload.macromedia.com/get/flashplayer/pdc/$VERSION/install_flash_player_11_linux.$ARCH.tar.gz"
+TAR=      # empty = auto
+DIR=.      # empty = auto
+DOCS="readme.txt"
+SLKFILES=""
 
-
-# Just in case:
-case "$ARCH" in
-  i?86) TARBALLARCH="i386" ; LIBDIRSUFFIX="" ; ARCH=i386 ;;
-  x86_64) TARBALLARCH="x86_64" ; LIBDIRSUFFIX="64" ;;
-esac
-
-
-
-SOURCE="http://fpdownload.macromedia.com/get/flashplayer/current/install_flash_player_11_linux.$TARBALLARCH.tar.gz"
-
-# Download binary tarball if still not present
-if [ ! -e $CWD/install_flash_player_11_linux.$TARBALLARCH.tar.gz ]; then
-    wget -c $SOURCE
+# If EULA
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])"
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
 fi
 
-# Create building directory
-rm -rf $PKG
+# Does not touch following if not needed
+JOBS=${JOBS:--j2}
+CWD=$(pwd)
+TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
+PKG=$TMP/package-$PKGNAME
+OUTPUT=${OUTPUT:-$CWD}
+TAR=${TAR:-$(basename $SOURCE)}
+DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
+
+if [ ! -e "$CWD/$TAR" ];then
+  wget "$SOURCE" -O "$CWD/$TAR"
+fi
+
+CHOST="i486"
+if [ "$ARCH" = "i486" ]; then
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+  CHOST="x86_64"
+fi
+
+### Preparing Source
+rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
-
-
-# Decompress the source tarball
-cd $TMP
-tar xzvf $CWD/install_flash_player_11_linux.$TARBALLARCH.tar.gz
-
-echo -e "\E[0;32m+--------------------------------------+\E[0;0m"
-echo -e "\E[0;32m| Start SlackBuild Flash Player Plugin |\E[0;0m"
-echo -e "\E[0;32m+--------------------------------------+\E[0;0m"
-
-# Installing Flash Player library
- install -m 0755 -p -D libflashplayer.so $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins/libflashplayer.so
-
-cp -a -r usr $PKG
-
-# Installing basic config file
-mkdir -p $PKG/etc/adobe
-cat << EOF > $PKG/etc/adobe/mms.cfg.new
-# Set EnableLinuxHWVideoDecode=1 to enable hardware acceleration
-EnableLinuxHWVideoDecode=0
-EOF
-
-#Add documentation files: readme, changelog and so on
-mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
-# Also add the slack-desk file and this slackbuild to the package
-mkdir -p $PKG/install
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
-cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/slack-desc > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-desc
-cat $CWD/$PKGNAME.SlackBuild > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$PKGNAME.SlackBuild
-
-
-# Building some post-install execution script 	
-	echo "if [ -x /usr/bin/update-mime-database ]; then
-  /usr/bin/update-mime-database /usr/share/mime &> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/update-desktop-database ]; then
-  /usr/bin/update-desktop-database 1> /dev/null 2> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/gtk-update-icon-cache ]; then
-  /usr/bin/gtk-update-icon-cache  -f -q /usr/share/icons/hicolor 1> /dev/null 2> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-
-
-# Find and print dependencies into slack-required file
 cd $PKG
-chown -R root:root $PKG
-chmod -R u+w,go+r-w,a-s .
-if [ -x /usr/bin/requiredbuilder ];then
-requiredbuilder -y -v -s  $CWD $PKG
-fi
-# Create txz package
-/sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
+tar xvf $CWD/$TAR
+cd $DIR
 
+
+chown -R root:root .
+chmod -R u+w,go+r-w,a-s .
+
+# Customize as you need
+mkdir -p usr/lib$LIBDIRSUFFIX/mozilla/plugins
+mv libflashplayer.so usr/lib$LIBDIRSUFFIX/mozilla/plugins
+
+# Documentations
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
+ 
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
+cd $CWD
+for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT $SLKFILES;do
+  [ -e $SB ]&&cp -r $SB $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$SB
+done
+
+if [ -d $PKG/usr/man ]; then
+    ( cd $PKG/usr/man
+      find . -type f -exec gzip -9 {} \;
+      for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+    )
+fi
+
+( cd $PKG
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+)
+
+mkdir -p $PKG/install
+cat $CWD/slack-desc > $PKG/install/slack-desc
+[ -e $CWD/doinst.sh ] && cat $CWD/doinst.sh > $PKG/install/doinst.sh
+[ -e $CWD/doinst.sh.gz ] && zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
+
+cd $PKG
+rm -f readme.txt
+chown -R root:root $PKG
+
+if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
+  requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
+  [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
+fi
+
+/sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
 
 if [ "$1" = "--cleanup" ]; then
   rm -rf $TMP
 fi
-
