Repository slackware:         openjdk         openjre         dropbox

diff --git a/slackware/network/dropbox/dropbox.SlackBuild b/slackware/network/dropbox/dropbox.SlackBuild
--- a/slackware/network/dropbox/dropbox.SlackBuild
+++ b/slackware/network/dropbox/dropbox.SlackBuild
@@ -1,10 +1,10 @@
 #!/bin/sh
+ 
 # Heavily based on the Slackware 14.0 SlackBuild
-# http://www.dropbox.com/
-# Packager Andrea Sciucca Gohanz ( gohanz at infinito.it)
-# Thanks to Murat D. Kadirov <banderols@gmail.com>
-# http://www.slacky.eu
-#
+# Written by miklos < ardutu @ gmail dot com >
+# 
+# Slackware build script for dropbox
+# Official Site: http://www.dropbox.com/
 #
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -23,51 +23,74 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-#
-# Exit on most errors
+# Require:
+
 set -e
 
-
-
-# Set variables:
-CWD=`pwd`
-OUTPUT=${OUTPUT:-$CWD}
+# Basic information.
 PKGNAME=dropbox
-TMP=${TMP:-/tmp/txz/$PKGNAME}
-PKG=$TMP/package
-VERSION=${VERSION:-1.2.49} 
-ARCH=${ARCH:-i686}  # i686 or x86_64
-BUILD=${BUILD:-3}
+VERSION=${VERSION:-2.2.9}
+BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
-
+ARCH=${ARCH:-i486}
 # Just in case:
 case "$ARCH" in
   i?86) TARBALLARCH="x86" ; LIBDIRSUFFIX=""  ;;
   x86_64) TARBALLARCH="x86_64" ; LIBDIRSUFFIX="64" ;;
 esac
-
-
-# Download sorce tarball if still not present
 SOURCE="http://dl-web.dropbox.com/u/17/$PKGNAME-lnx.$TARBALLARCH-$VERSION.tar.gz"
+TAR=      # empty = auto
+DIR=.$PKGNAME-dist
+DOCS="README VERSION"
+SLKFILES="dropbox.desktop dropbox.png" # all files needed to the slackbuild (except slack-desc etc..)
 
-if [ ! -e $CWD/$PKGNAME-lnx.$TARBALLARCH-$VERSION.tar.gz ]; then
- wget $SOURCE
+# An EULA for non-free packages
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])":
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
 fi
 
-# Create building directory
-rm -rf $PKG
+# Does not touch following if not needed
+JOBS=${JOBS:--j2}
+CWD=$(pwd)
+TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
+PKG=$TMP/package-$PKGNAME
+OUTPUT=${OUTPUT:-$CWD}
+TAR=${TAR:-$(basename $SOURCE)}
+DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
+ 
+if [ ! -e "$CWD/$TAR" ];then
+  wget "$SOURCE" -O "$CWD/$TAR"
+fi
+ 
+CHOST="i486"
+if [ "$ARCH" = "i486" ]; then
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+  CHOST="x86_64"
+fi
+
+### Preparing Source
+rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
-
-# Decompress the source tarball
 cd $TMP
-tar xvzf $CWD/$PKGNAME-lnx.$TARBALLARCH-$VERSION.tar.gz
-
-echo -e "\E[0;32m+--------------------------+\E[0;0m"
-echo -e "\E[0;32m| Start SlackBuild Dropbox |\E[0;0m"
-echo -e "\E[0;32m+--------------------------+\E[0;0m"
-
-# Adjust permissions and ownerships
-cd .$PKGNAME-dist
+tar xvf $CWD/$TAR
+cd $DIR
+ 
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
@@ -85,49 +108,50 @@ chmod 755 $PKG/usr/bin/*
 mkdir $PKG/opt
 mkdir -p $PKG/usr/bin
 cp -R ../.$PKGNAME-dist $PKG/opt/dropbox
-rm $PKG/opt/dropbox/libstdc++.so.6
 install -m 0644 -p -D $CWD/dropbox.desktop $PKG/usr/share/applications/dropbox.desktop
 install -m 0644 -p -D $CWD/dropbox.png     $PKG/usr/share/pixmaps/dropbox.png
 
-
-
-# Add documentation files: readme, changelog and so on
+# Documentations
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
+ 
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
-chmod 644 $PKG/usr/doc/$PKGNAME-$VERSION/*
+cd $CWD
+for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT $SLKFILES;do
+  [ -e $SB ]&&cp -r $SB $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$SB
+done
 
+if [ -d $PKG/usr/man ]; then
+    ( cd $PKG/usr/man
+      find . -type f -exec gzip -9 {} \;
+      for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+    )
+fi
 
-# Also add the slack-desk file and this slackbuild to the package
+if [ -d $PKG/usr/info ]; then
+    ( cd $PKG/usr/info
+      find . -type f -exec gzip -9 {} \;
+      for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+    )
+fi
+
+# Preparing to packaging
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/slack-desc > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-desc
-cat $CWD/$PKGNAME.SlackBuild > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$PKGNAME.SlackBuild
+[ -e $CWD/doinst.sh ] && cat $CWD/doinst.sh > $PKG/install/doinst.sh
+[ -e $CWD/doinst.sh.gz ] && zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
-
-# Building some post-install execution script 	
-	echo "if [ -x /usr/bin/update-desktop-database ]; then
-  /usr/bin/update-desktop-database 1> /dev/null 2> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/gtk-update-icon-cache ]; then
-  /usr/bin/gtk-update-icon-cache  -f -q /usr/share/icons/hicolor 1> /dev/null 2> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-
-
-
-
-# Find and print dependencies into slack-required file
 cd $PKG
 chown -R root:root $PKG
-if [ -x /usr/bin/requiredbuilder ];then
-requiredbuilder -y -v -s  $CWD $PKG
+ 
+if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
+  requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
+  [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
-# Create txz package
+
+# Packaging
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
-
-
-# Cleanup if enabled
+ 
 if [ "$1" = "--cleanup" ]; then
- rm -rf $TMP
+  rm -rf $TMP
 fi
-
