Repository slackware:         smplayer         skype

diff --git a/slackware/multimedia/smplayer/smplayer.SlackBuild b/slackware/multimedia/smplayer/smplayer.SlackBuild
--- a/slackware/multimedia/smplayer/smplayer.SlackBuild
+++ b/slackware/multimedia/smplayer/smplayer.SlackBuild
@@ -1,10 +1,8 @@
 #!/bin/sh
-
+ 
 # Heavily based on the Slackware 14.0 SlackBuild
 # Written by Andrea Sciucca Gohanz ( gohanz at infinito.it )
-# Thanks to  Flamelab <panosfilip@gmail.com>
-# Thanks to  WAntilles <wantilles@adslgr.com>
-# Thanks to Erik Hanson  erik@slackbuilds.org
+# Last build from miklos < ardutu at gmail dot com >
 
 # Slackware build script for smplayer
 # Official Site: http://smplayer.sourceforge.net
@@ -26,127 +24,86 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# Exit on most errors
-set -e 
+# Require:
 
+set -e
 
-
-# Set variables:
-CWD=`pwd`
-OUTPUT=${OUTPUT:-$CWD}
+# Basic information.
 PKGNAME=smplayer
-TMP=${TMP:-/tmp/txz/$PKGNAME}
-PKG=$TMP/package
-VERSION=${VERSION:-0.8.4}
-FREEVER=${FREEVER:-20120919}
-NONFVER=${NONFVER:-0.1.1}
-ARCH=${ARCH:-i486}
-JOBS=${JOBS:--j2}
+VERSION=${VERSION:-0.8.5}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
+ARCH=${ARCH:-i486}
+SOURCE="http://downloads.sourceforge.net/project/smplayer/SMPlayer/$VERSION/$PKGNAME-$VERSION.tar.bz2"
+TAR=      # empty = auto
+DIR=      # empty = auto
+DOCS="Changelog *.txt"
+SLKFILES="" # all files needed to the slackbuild (except slack-desc etc..)
 
-SOURCE="http://downloads.sourceforge.net/project/smplayer/SMPlayer/0.8.4/$PKGNAME-$VERSION.tar.bz2"
-
-# Download sorce tarball if still not present
-if [ ! -e $CWD/$PKGNAME-$VERSION.tar.bz2 ]; then
-wget -c $SOURCE
+# An EULA for non-free packages
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])":
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
 fi
 
-SOURCE="http://downloads.sourceforge.net/project/smplayer/SMPlayer-themes/$FREEVER/smplayer-themes-$FREEVER.tar.bz2"
-
-# Download sorce tarball if still not present
-if [ ! -e $CWD/smplayer-themes-$FREEVER.tar.bz2 ]; then
-wget -c $SOURCE
+# Does not touch following if not needed
+JOBS=${JOBS:--j2}
+CWD=$(pwd)
+TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
+PKG=$TMP/package-$PKGNAME
+OUTPUT=${OUTPUT:-$CWD}
+TAR=${TAR:-$(basename $SOURCE)}
+DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
+ 
+if [ ! -e "$CWD/$TAR" ];then
+  wget "$SOURCE" -O "$CWD/$TAR"
 fi
-
-SOURCE="http://downloads.sourceforge.net/project/smplayer/SMPlayer-themes-nonfree/$NONFVER/smplayer-themes-nonfree-$NONFVER.tar.bz2"
-
-# Download sorce tarball if still not present
-if [ ! -e $CWD/smplayer-themes-nonfree-$NONFVER.tar.bz2 ]; then
-wget -c $SOURCE
-fi
-
-# Set compiling FLAGS
+ 
+CHOST="i486"
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"; SLKLDFLAGS=""; LIBDIRSUFFIX=""; CHOST="i486"
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"; SLKLDFLAGS=""; LIBDIRSUFFIX=""; CHOST="i686"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"; SLKLDFLAGS="-L/usr/lib64"; LIBDIRSUFFIX="64"; CHOST="x86_64"
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+  CHOST="x86_64"
 fi
 
-# Create building directory
-rm -rf $PKG
+### Preparing Source
+rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
-
-# Decompress the source tarball
 cd $TMP
-tar xvjf $CWD/$PKGNAME-$VERSION.tar.bz2
+tar xvf $CWD/$TAR
+cd $DIR
 
-echo -e "\E[0;32m+---------------------------+\E[0;0m"
-echo -e "\E[0;32m| Start SlackBuild SMPlayer |\E[0;0m"
-echo -e "\E[0;32m+---------------------------+\E[0;0m"
-
-# Adjust permissions and ownerships
-cd $PKGNAME-$VERSION
-# Fix DOC_PATH and CONF_PATH
-sed -i "s%share/doc/packages/smplayer%doc/$PKGNAME-$VERSION%" Makefile
-sed -i "s%^CONF_PREFIX%#CONF_PREFIX%" Makefile
-chmod -R u+w,go+r-w,a-s .
 chown -R root:root .
+chmod -R u+w,go+r-w,a-s .
 
-make $JOBS PREFIX=/usr
-make install PREFIX=/usr DESTDIR=$PKG
+sed -i '2s|/local||;8s|/share.*|/doc/'"$PKGNAME-$VERSION"'|;78,80s|share/||g' Makefile
+make $JOBS
+make install DESTDIR=$PKG
 
-
-# Strip binaries and shared objects, if present
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
-  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
-)
-
-
-# Use CONF_PATH
-mkdir -p $PKG/etc/smplayer
-mv $PKG/usr/share/smplayer/input.conf $PKG/etc/smplayer/input.conf.new
-ln -s /etc/smplayer/input.conf $PKG/usr/share/smplayer/input.conf
-
-# Fix desktop file menu
-sed -i 's|Exec=smplayer %U|Exec=smplayer %F|' $PKG/usr/share/applications/smplayer.desktop
-sed -i 's|Exec=smplayer -add-to-playlist %U|Exec=smplayer -add-to-playlist %F|' \
-        $PKG/usr/share/applications/smplayer_enqueue.desktop
-
-
-#Add documentation files: readme, changelog and so on
+# Documentations
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
+ 
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
-cp -a Changelog *.txt \
-$PKG/usr/doc/$PKGNAME-$VERSION
-chmod 644 $PKG/usr/doc/$PKGNAME-$VERSION/*
+cd $CWD
+for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT $SLKFILES;do
+  [ -e $SB ]&&cp -r $SB $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$SB
+done
 
-
-# Also add the slack-desk file and this slackbuild to the package
-mkdir -p $PKG/install
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
-cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/slack-desc > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-desc
-cat $CWD/$PKGNAME.SlackBuild > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$PKGNAME.SlackBuild
-
-
-# Installing extra themes 
-( tar xvf $CWD/smplayer-themes-$FREEVER.tar.bz2
-  cd smplayer-themes-$FREEVER
-  make PREFIX=/usr DESTDIR=$PKG install )
-
-
-# Installing extra themes  nonfree
-( tar xvjf $CWD/smplayer-themes-nonfree-$NONFVER.tar.bz2
-  cd smplayer-themes-nonfree-$NONFVER
-  make PREFIX=/usr DESTDIR=$PKG install )
-
-
-# Compress the man pages if present
-mv $PKG/usr/share/man $PKG/usr
 if [ -d $PKG/usr/man ]; then
     ( cd $PKG/usr/man
       find . -type f -exec gzip -9 {} \;
@@ -154,23 +111,31 @@ if [ -d $PKG/usr/man ]; then
     )
 fi
 
+# Strip binary files
+( cd $PKG
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+)
 
 
+# Preparing to packaging
+mkdir -p $PKG/install
+cat $CWD/slack-desc > $PKG/install/slack-desc
+[ -e $CWD/doinst.sh ] && cat $CWD/doinst.sh > $PKG/install/doinst.sh
+[ -e $CWD/doinst.sh.gz ] && zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
-# Find and print dependencies into slack-required file
 cd $PKG
 chown -R root:root $PKG
-if [ -x /usr/bin/requiredbuilder ];then
-requiredbuilder -y -v -b -s  $CWD $PKG
+ 
+if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
+  requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
+  [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
-# Create txz package
+
+# Packaging
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
-
-
-# Cleanup if enabled
+ 
 if [ "$1" = "--cleanup" ]; then
- rm -rf $TMP
+  rm -rf $TMP
 fi
-
-
-
