Repository slackware:         Twisted         kdesvn         kdiff3         icedtea-web         libktorrent         libtorrent-rasterbar         pygame         rlog         portmidi         deluge         knemo         ktorrent         leechcraft         KBookocr         cuneiform         keepassx         encfs         kdirwatch         kencfs         kdocker         krecipes

diff --git a/slackware/libraries/icedtea-web/icedtea-web.SlackBuild b/slackware/libraries/icedtea-web/icedtea-web.SlackBuild
--- a/slackware/libraries/icedtea-web/icedtea-web.SlackBuild
+++ b/slackware/libraries/icedtea-web/icedtea-web.SlackBuild
@@ -1,12 +1,13 @@
 #!/bin/sh
- 
+
 # Heavily based on the Slackware 14.0 SlackBuild
-# Written by Loris Vincenzi (info@slacky.it)
-# Last build from Loris Vincenzi (info@slacky.it)
-# 
-# Slackware build script for twisted
-# Official Site: http://twistedmatrix.com/trac
-#
+
+# Written by Matteo Rossini ( zerouno [at] slacky.it )
+# Last build from Matteo Rossini ( zerouno [at] slacky.it )
+
+# Slackware build script for icedtea-web
+# Official Site: http://icedtea.classpath.org/wiki/IcedTea-Web
+
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
 #
@@ -24,21 +25,34 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# Require: zope.interface
+# Require: 
 
 set -e
 
-PKGNAME=Twisted
-VERSION=${VERSION:-12.2.0}
-BUILD=${BUILD:-2}
+# Basic information. 
+PKGNAME=icedtea-web
+VERSION=${VERSION:-1.3}
+BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
-ARCH=${ARCH:-i486}
-SOURCE="http://pypi.python.org/packages/source/T/Twisted/$PKGNAME-$VERSION.tar.bz2"
-TAR=
-DIR=
-DOCS="LICENSE README"
+ARCH=${ARCH:-i686}
+SOURCE="http://icedtea.classpath.org/download/source/icedtea-web-$VERSION.tar.gz"
+TAR=      # empty = auto
+DIR=      # empty = auto
+DOCS="AUTHORS COPYING ChangeLog NEWS README"
 SLKFILES=""
 
+# If EULA
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])"
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
+fi
+
+# Does not touch following if not needed
 JOBS=${JOBS:--j2}
 CWD=$(pwd)
 TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
@@ -46,11 +60,11 @@ PKG=$TMP/package-$PKGNAME
 OUTPUT=${OUTPUT:-$CWD}
 TAR=${TAR:-$(basename $SOURCE)}
 DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
- 
-if [ ! -e "$CWD/$TAR" ];then
-  wget "$SOURCE" -O "$CWD/$TAR"
+
+if [ ! -e $CWD/$TAR ];then
+  wget $SOURCE # -O "$CWD/$TAR"
 fi
- 
+
 CHOST="i486"
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -67,18 +81,52 @@ elif [ "$ARCH" = "x86_64" ]; then
   CHOST="x86_64"
 fi
 
+### Preparing Source
 rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 tar xvf $CWD/$TAR
 cd $DIR
- 
+
+
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
-python setup.py build
-python setup.py install --root=$PKG
+# Customize as you need
+[ ! -x configure  ] && ./autogen.sh
+sed -i -e 's/mozilla-plugin/seamonkey-plugin/g' configure
 
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
+./configure \
+  --prefix=/usr \
+  --libdir=/usr/lib$LIBDIRSUFFIX \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/$PKGNAME-$VERSION \
+  --with-jdk-home=/usr/lib${LIBDIRSUFFIX}/java \
+  --with-jre-home=/usr/lib${LIBDIRSUFFIX}/java/jre \
+  --with-pkgversion=$(cat /etc/slackware-version |tr ' ' '-')-$ARCH \
+  --disable-docs \
+  --build=$CHOST-slackware-linux
+make $JOBS
+make install DESTDIR=$PKG
+
+## Do special operations
+
+#sed -i -e "s,java/jre/bin,java/bin,g" $PKG/usr/bin/javaws
+#sed -i -e "s,java/jre/bin,java/bin,g" $PKG/usr/bin/itweb-settings
+
+mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
+ln -sf /usr/lib${LIBDIRSUFFIX}/IcedTeaPlugin.so $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
+mkdir -p $PKG/usr/share/{applications,pixmaps}
+cp javaws.png $PKG/usr/share/pixmaps/
+install -m 0644 javaws.desktop $PKG/usr/share/applications/
+install -m 0644 itweb-settings.desktop $PKG/usr/share/applications/
+
+
+# Documentations
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
 cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
  
@@ -108,14 +156,14 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
 chown -R root:root $PKG
- 
+
 if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
-    ADD="$(cd /var/log/packages;ls zope.interface-*|sed -r 's/zope.interface-/zope.interface >= /')" requiredbuilder -y -v -s $CWD $PKG
-  [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
+  requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
+  cat $CWD/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
 
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
- 
+
 if [ "$1" = "--cleanup" ]; then
   rm -rf $TMP
 fi
