Repository slackware64:         speex Repository slackware:         calibre         fotoxx         mashup         ufraw         Image-ExifTool         daq         gtkimageview         libdnet         aria2         snort

diff --git a/slackware64/multimedia/speex/speex.SlackBuild b/slackware64/multimedia/speex/speex.SlackBuild
--- a/slackware64/multimedia/speex/speex.SlackBuild
+++ b/slackware64/multimedia/speex/speex.SlackBuild
@@ -1,12 +1,13 @@
 #!/bin/sh
- 
+
 # Heavily based on the Slackware 14.0 SlackBuild
-# Written by Luciano Fattore (luffatt at gmail dot com)
-# Last build from Loris Vincenzi (info@slacky.it)
-# 
-# Slackware build script for calibre
-# Official Site: http://calibre-ebook.com/
-#
+
+# Written by Davide
+# Last build from albatros_la aka AsPh4lTo ( albatros_la@hotmail.com )
+
+# Slackware build script for speex
+# Official Site: http://www.speex.org
+
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
 #
@@ -23,21 +24,29 @@
 # WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-#
-# Require:
 
 set -e
 
-PKGNAME=calibre
-VERSION=${VERSION:-0.9.8}
+PKGNAME=speex
+VERSION=${VERSION:-1.2rc1}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
-ARCH=${ARCH:-i686}
-SOURCE="http://downloads.sourceforge.net/project/$PKGNAME/$VERSION/$PKGNAME-$VERSION-i686.tar.bz2"
-TAR=
-DIR=$PKGNAME-$VERSION-i686
-DOCS="COPYRIGHT INSTALL LICENSE.rtf Changelog.yaml LICENSE README"
-SLKFILES=""
+ARCH=${ARCH:-x86_64}
+SOURCE="http://downloads.xiph.org/releases/speex/$PKGNAME-$VERSION.tar.gz"
+TAR=      # empty = auto
+DIR=      # empty = auto
+DOCS="AUTHORS COPYING ChangeLog INSTALL NEWS README* TODO"
+SLKFILES="" 
+
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])"
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
+fi
 
 JOBS=${JOBS:--j2}
 CWD=$(pwd)
@@ -46,11 +55,11 @@ PKG=$TMP/package-$PKGNAME
 OUTPUT=${OUTPUT:-$CWD}
 TAR=${TAR:-$(basename $SOURCE)}
 DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
- 
-if [ ! -e "$CWD/$TAR" ];then
-  wget "$SOURCE" -O "$CWD/$TAR"
+
+if [ ! -e $CWD/$TAR ];then
+  wget $SOURCE -O "$CWD/$TAR"
 fi
- 
+
 CHOST="i486"
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -68,39 +77,33 @@ elif [ "$ARCH" = "x86_64" ]; then
 fi
 
 rm -rf $TMP
-mkdir -p $TMP/$PKGNAME $PKG $OUTPUT
-cd $TMP/$PKGNAM
+mkdir -p $TMP $PKG $OUTPUT
+cd $TMP
 tar xvf $CWD/$TAR
- 
+cd $DIR
+
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
-curl -L http://status.calibre-ebook.com/dist/src | tar xvJ 
-cd calibre*
-python setup.py install --prefix=$PKG/usr
-
-for file in $(find $PKG/usr -iname "*.recipe") ; do
-   (sed -i -e "s|/tmp/buildpkgs/calibre/package-calibre||g" $file)
-done
-for file in $(find $PKG/usr/bin/*) ; do
-   (sed -i -e "s|/tmp/buildpkgs/calibre/package-calibre||g" $file)
-done
-for file in $(find $PKG/usr -iname "*.py") ; do
-   (sed -i -e "s|/tmp/buildpkgs/calibre/package-calibre||g" $file)
-done
-mv $PKG/usr/etc $PKG/etc
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
+./configure \
+  --prefix=/usr \
+  --libdir=/usr/lib$LIBDIRSUFFIX \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --mandir=/usr/man \
+  --disable-static \
+  --build=$CHOST-slackware-linux
+make $JOBS
+make install DESTDIR=$PKG
 
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
 cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
-
-mkdir -p $PKG/usr/share/applications
-cp -a $CWD/*.desktop $PKG/usr/share/applications
-mkdir -p $PKG/usr/share/icons/hicolor/128x128/apps/
-cp -a $CWD/*.png $PKG/usr/share/icons/hicolor/128x128/apps/
  
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
 cd $CWD
-for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT calibre-gui.png calibre-viewer.png calibre-ebook-viewer.desktop calibre-gui.desktop $SLKFILES;do
+for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT $SLKFILES;do
   [ -e $SB ]&&cp -r $SB $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$SB
 done
 
@@ -124,24 +127,14 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
 chown -R root:root $PKG
- 
+
 if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
-  ADD=$(ls /var/log/packages/ | sed -ne 's/\(beautifulsoup4\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(Imaging\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(cssutils\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(dnspython\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(lxml\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(mechanize\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(ez_setup\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(netifaces\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(PyQt\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(python-dateutil\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2/p') \
   requiredbuilder -y -v -s $CWD $PKG
   [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
 
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
- 
+
 if [ "$1" = "--cleanup" ]; then
   rm -rf $TMP
 fi
