Repository slackware:         bluefish         flash-player-plugin

diff --git a/slackware/development/bluefish/bluefish.SlackBuild b/slackware/development/bluefish/bluefish.SlackBuild
--- a/slackware/development/bluefish/bluefish.SlackBuild
+++ b/slackware/development/bluefish/bluefish.SlackBuild
@@ -1,8 +1,10 @@
 #!/bin/sh
+ 
 # Heavily based on the Slackware 14.0 SlackBuild
-# http://www.bluefish.openoffice.nl
-# Packager Vincenzi Loris - slacky@slacky.it
-# http://www.slacky.eu
+# Written by miklos < ardutu at gmail dot com >
+# 
+# Slackware build script for bluefish
+# Official Site: http://bluefish.openoffice.nl
 #
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -21,116 +23,96 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-#
-# Exit on most errors
+# Require:
+
 set -e
 
-
-
-# Set variables:
-CWD=`pwd`
-OUTPUT=${OUTPUT:-$CWD}
+# Basic information.
 PKGNAME=bluefish
-TMP=${TMP:-/tmp/txz/$PKGNAME}
-PKG=$TMP/package
-VERSION=${VERSION:-2.2.3}
-ARCH=${ARCH:-i486}
-JOBS=${JOBS:--j2}
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-2.2.4}
+BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
+ARCH=${ARCH:-i486}
+SOURCE="http://www.bennewitz.com/bluefish/stable/source/${PKGNAME}-${VERSION}.tar.bz2"
+TAR=      # empty = auto
+DIR=      # empty = auto
+DOCS="AUTHORS COPYING INSTALL ChangeLog NEWS README TODO"
+SLKFILES="" # all files needed to the slackbuild (except slack-desc etc..)
 
-SOURCE="http://www.bennewitz.com/bluefish/stable/source/$PKGNAME-$VERSION.tar.bz2"
-
-# Download sorce tarball if still not present
-if [ ! -e $PKGNAME-$VERSION.tar.bz2 ]; then
-wget -c $SOURCE
+# An EULA for non-free packages
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])":
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
 fi
 
-
-
-# Set compiling FLAGS
+# Does not touch following if not needed
+JOBS=${JOBS:--j2}
+CWD=$(pwd)
+TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
+PKG=$TMP/package-$PKGNAME
+OUTPUT=${OUTPUT:-$CWD}
+TAR=${TAR:-$(basename $SOURCE)}
+DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
+ 
+if [ ! -e "$CWD/$TAR" ];then
+  wget "$SOURCE" -O "$CWD/$TAR"
+fi
+ 
+CHOST="i486"
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"; SLKLDFLAGS=""; LIBDIRSUFFIX=""; CHOST="i486"
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"; SLKLDFLAGS=""; LIBDIRSUFFIX=""; CHOST="i686"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"; SLKLDFLAGS="-L/usr/lib64"; LIBDIRSUFFIX="64"; CHOST="x86_64"
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+  CHOST="x86_64"
 fi
 
-# Creaye building directory
-rm -rf $PKG
+### Preparing Source
+rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
-
-# Decompress the source tarball
 cd $TMP
-tar xvjf $CWD/$PKGNAME-$VERSION.tar.bz2
-
-echo -e "\E[0;32m+---------------------------+\E[0;0m"
-echo -e "\E[0;32m| Start SlackBuild Bluefish |\E[0;0m"
-echo -e "\E[0;32m+---------------------------+\E[0;0m"
-
-# Adjust permissions and ownerships
-cd $PKGNAME-$VERSION
-chmod -R u+w,go+r-w,a-s .
+tar xvf $CWD/$TAR
+cd $DIR
+ 
 chown -R root:root .
+chmod -R u+w,go+r-w,a-s .
 
-
-LDFLAGS="$SLKLDFLAGS" \
+# Customize as you need
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
-./configure 	--prefix=/usr \
-		--sysconfdir=/etc \
-		--localstatedir=/var \
-		--libdir=/usr/lib${LIBDIRSUFFIX} \
-		--mandir=/usr/man \
-		--infodir=/usr/info \
-		--docdir=/usr/doc/$PKGNAME-$VERSION \
-		--program-prefix= \
-		--program-suffix= \
-		--build=$CHOST-slackware-linux
-# Build and install
+./configure \
+  --prefix=/usr \
+  --libdir=/usr/lib$LIBDIRSUFFIX \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/$PKGNAME-$VERSION \
+  --build=$CHOST-slackware-linux
 make $JOBS
 make install DESTDIR=$PKG
 
-
-# Strip binaries and shared objects, if present
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
-  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
-)
-
-
-#Add documentation files: readme, changelog and so on
+# Documentations
+mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
+cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
+ 
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
-cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README TODO $PKG/usr/doc/$PKGNAME-$VERSION
-chmod 644 $PKG/usr/doc/$PKGNAME-$VERSION/*
+cd $CWD
+for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT $SLKFILES;do
+  [ -e $SB ]&&cp -r $SB $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$SB
+done
 
-
-
-# Also add the slack-desk file and this slackbuild to the package
-mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/slack-desc > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-desc
-cat $CWD/$PKGNAME.SlackBuild > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$PKGNAME.SlackBuild
-
-
-	echo "if [ -x /usr/bin/update-mime-database ]; then
-  /usr/bin/update-mime-database /usr/share/mime &> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/update-desktop-database ]; then
-  /usr/bin/update-desktop-database &> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/gtk-update-icon-cache ]; then
-  /usr/bin/gtk-update-icon-cache  -f -q /usr/share/icons/hicolor &> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-
-
-
-# Compress the man pages if present
 if [ -d $PKG/usr/man ]; then
     ( cd $PKG/usr/man
       find . -type f -exec gzip -9 {} \;
@@ -138,23 +120,39 @@ if [ -d $PKG/usr/man ]; then
     )
 fi
 
+if [ -d $PKG/usr/info ]; then
+    ( cd $PKG/usr/info
+      find . -type f -exec gzip -9 {} \;
+      for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
+    )
+fi
 
 
-# Find and print dependencies into slack-required file
+# Strip binary files
+( cd $PKG
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
+)
+
+
+# Preparing to packaging
+mkdir -p $PKG/install
+cat $CWD/slack-desc > $PKG/install/slack-desc
+[ -e $CWD/doinst.sh ] && cat $CWD/doinst.sh > $PKG/install/doinst.sh
+[ -e $CWD/doinst.sh.gz ] && zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
+
 cd $PKG
 chown -R root:root $PKG
-if [ -x /usr/bin/requiredbuilder ];then
-requiredbuilder -y -v -s  $CWD $PKG
+ 
+if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
+  requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
+  [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
-# Create txz package
+
+# Packaging
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
-
-
-# Cleanup if enabled
+ 
 if [ "$1" = "--cleanup" ]; then
- rm -rf $TMP
+  rm -rf $TMP
 fi
-
-
-
-
