Repository slackware64:         kde-gtk-config         qtcurve-gtk2         calibre         cuetools         gcue2tracks         shntool

diff --git a/slackware64/multimedia/gcue2tracks/gcue2tracks.SlackBuild b/slackware64/multimedia/gcue2tracks/gcue2tracks.SlackBuild
--- a/slackware64/multimedia/gcue2tracks/gcue2tracks.SlackBuild
+++ b/slackware64/multimedia/gcue2tracks/gcue2tracks.SlackBuild
@@ -1,14 +1,14 @@
 #!/bin/sh
- 
+
 # Heavily based on the Slackware 14.0 SlackBuild
-# Written by Luciano Fattore (luffatt at gmail dot com)
-# Thank to Larry Hajali <larryhaja[at]gmail[dot]com>
-# Last build from 6c33c (seic33c AT gmail DOT com)
-# Patches from Alien Bob and SlackBuild.org
-# 
-# Slackware build script for calibre
-# Official Site: http://calibre-ebook.com/
-#
+
+# Written by Andrea Sciucca ( gohanz at infinito.it)
+# Last build from 6c33c ( seic33c [at] gmail [dot] com )
+
+# Slackware build script for gcue2tracks
+# Official Site: http://trac-hg.assembla.com/gCue2tracks/wiki
+# Patches from ...
+
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
 #
@@ -26,33 +26,47 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# Require:
+# Requirements: cuetools, ffmpeg, mac, shntool
 
 set -e
 
-PKGNAME=calibre
-VERSION=${VERSION:-0.9.33}
+# Basic informatapion.
+PKGNAME=gcue2tracks
+VERSION=${VERSION:-0.5.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
 ARCH=${ARCH:-x86_64}
-SOURCE="http://downloads.sourceforge.net/$PKGNAME/$PKGNAME-$VERSION.tar.xz"
-TAR=
-DIR=$PKGNAME
-DOCS="COPYRIGHT INSTALL LICENSE* Changelog.yaml LICENSE* README*"
-SLKFILES="*.patch"
+SOURCE="https://www.assembla.com/spaces/gCue2tracks/documents/bgg6jqEgGr4PptacwqEsg8/download/bgg6jqEgGr4PptacwqEsg8"
+TAR=$PKGNAME-$VERSION.tar.gz     # empty = auto
+DIR=gCue2tracks      # empty = auto
+DOCS=""
+SLKFILES=""
+ADDREQUIRED="cuetools >= 1.3.1-x86_64-1sl, ffmpeg >= 1.2-x86_64-3sl, mac >= 3.99-u4-b5-x86_64-1sl, shntool >= 3.0.10-x86_64-1sl"
 
+# If EULA
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])"
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
+fi
+
+# Do not touch following if not needed
 JOBS=${JOBS:--j2}
 CWD=$(pwd)
 TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
 PKG=$TMP/package-$PKGNAME
 OUTPUT=${OUTPUT:-$CWD}
 TAR=${TAR:-$(basename $SOURCE)}
-DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|)$//')}
- 
-if [ ! -e "$CWD/$TAR" ];then
-  wget "$SOURCE" -O "$CWD/$TAR"
+DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|.tgz|)$//')}
+
+if [ ! -e $CWD/$TAR ];then
+  wget $SOURCE -O "$CWD/$PKGNAME-$VERSION.tar.gz"
 fi
- 
+
 CHOST="i486"
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -69,63 +83,30 @@ elif [ "$ARCH" = "x86_64" ]; then
   CHOST="x86_64"
 fi
 
+### Preparing Source
 rm -rf $TMP
-mkdir -p $TMP/$PKGNAME $PKG $OUTPUT
-cd $TMP/$PKGNAM
+mkdir -p $TMP $PKG $OUTPUT
+cd $TMP
 tar xvf $CWD/$TAR
 cd $DIR
-
-patch -p1 < $CWD/remove-desktop-integration.patch
-patch -p1 < $CWD/calibre-module-fix.patch
-patch -p1 < $CWD/fix-shebangs.patch
-patch -p1 < $CWD/calibre_noqthack.patch
 
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
-# calibre 0.9.33 fail to build because don't find src/caliblre/plugins directory
-# so we create one ;)
-mkdir -p src/calibre/plugins/
+python setup.py build
+python setup.py install --root=$PKG
 
-python setup.py install \
---root=$PKG \
---prefix=/usr \
---bindir=/usr/bin \
---libdir=/usr/lib${LIBDIRSUFFIX} \
---sharedir=/usr/share \
---staging-bindir=$PKG/usr/bin \
---staging-libdir=$PKG/usr/lib${LIBDIRSUFFIX} \
---staging-sharedir=$PKG/usr/share
+# Fix executable permission
+chmod 755 $PKG/usr/bin/*
 
+# Documentation
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
-cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
-
-mkdir -p $PKG/usr/share/applications
-cp -a $CWD/*.desktop $PKG/usr/share/applications
-mkdir -p $PKG/usr/share/icons/hicolor/
-
-( cd $PKG/usr/share/icons/hicolor
-  for res in 16 22 24 32 48 64 72 96 128 ; do
-    dir=${res}x${res}/apps
-    mkdir -p ${dir}
-    convert $CWD/calibre-gui.png -depth 8 -filter Lanczos \
-           -resize ${res}x${res} ${dir}/calibre-gui.png 
-    convert $CWD/calibre-viewer.png -depth 8 -filter Lanczos \
-           -resize ${res}x${res} ${dir}/calibre-viewer.png       
-  done
-)
-# remove fonts liberation-fonts-ttf and linking them to those already installed
-( 
- cd $PKG/usr/share/calibre/fonts/liberation/
- for FONT in *.ttf ; do
- rm $FONT
- ln -sf /usr/share/fonts/TTF/$FONT
- done
-)
+# no docs on this package :)
+#cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
 
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
 cd $CWD
-for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT calibre-gui.png calibre-viewer.png calibre-ebook-viewer.desktop calibre-gui.desktop $SLKFILES;do
+for SB in $PKGNAME.SlackBuild slack-desc doinst.sh doinst.sh.gz EULA.TXT $SLKFILES;do
   [ -e $SB ]&&cp -r $SB $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/$SB
 done
 
@@ -149,27 +130,15 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
 chown -R root:root $PKG
- 
+
 if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
-  ADD=$(ls /var/log/packages/ | sed -ne 's/\(beautifulsoup4\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(Imaging\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(cssselect\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(cssutils\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(dnspython\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(lxml\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(mechanize\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(psutil\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(pycrypto\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(ez_setup\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(netifaces\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(PyQt\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2,/p' \
-  -e 's/\(python-dateutil\)-\([^-]\+-[^-]\+-[^-]\+\)/\1 >= \2/p') \
+  ADD=$ADDREQUIRED \
   requiredbuilder -y -v -s $CWD $PKG
   [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
 
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
- 
+
 if [ "$1" = "--cleanup" ]; then
   rm -rf $TMP
 fi
