Repository slackware64:         gmtk Repository slackware:         scribus         atk         skype

diff --git a/slackware64/libraries/gmtk/gmtk.SlackBuild b/slackware64/libraries/gmtk/gmtk.SlackBuild
--- a/slackware64/libraries/gmtk/gmtk.SlackBuild
+++ b/slackware64/libraries/gmtk/gmtk.SlackBuild
@@ -1,11 +1,10 @@
 #!/bin/sh
  
 # Heavily based on the Slackware 14.0 SlackBuild
-# Written by Loris Vincenzi (info@slacky.it)
-# Last build from Loris Vincenzi (info@slacky.it)
+# Written by miklos < ardutu at gmail dot com >
 # 
-# Slackware build script for scribus
-# Official Site: http://www.scribus.org.uk/index.php
+# Slackware build script for gmtk
+# Official Site: http://code.google.com/p/gmtk/
 #
 # Redistribution and use of this script, with or without modification, is
 # permitted provided that the following conditions are met:
@@ -28,17 +27,30 @@
 
 set -e
 
-PKGNAME=scribus
-VERSION=${VERSION:-1.4.2}
+# Basic information.
+PKGNAME=gmtk
+VERSION=${VERSION:-1.0.7}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sl}
-ARCH=${ARCH:-i486}
-SOURCE="http://downloads.sourceforge.net/project/scribus/scribus/1.4.2/$PKGNAME-$VERSION.tar.xz"
-TAR=
-DIR=
-DOCS="BUILDING COPYING ChangeLog* LINKS NEWS"
-SLKFILES=""
+ARCH=${ARCH:-x86_64}
+SOURCE="http://gmtk.googlecode.com/files/${PKGNAME}-${VERSION}.tar.gz"
+TAR=      # empty = auto
+DIR=      # empty = auto
+DOCS="AUTHORS COPYING ChangeLog INSTALL NEWS README"
+SLKFILES="" # all files needed to the slackbuild (except slack-desc etc..)
 
+# An EULA for non-free packages
+if [ -e EULA.TXT ];then
+  more EULA.TXT
+  echo "Do you accept terms? (yes/[no])":
+  read ACCEPT
+  if [ "$ACCEPT" != "yes" ];then
+    echo; echo "SlackBuild Aborted!!"
+    exit 1
+  fi
+fi
+
+# Does not touch following if not needed
 JOBS=${JOBS:--j2}
 CWD=$(pwd)
 TMP=${TMP:-/tmp/buildpkgs/$PKGNAME}
@@ -67,6 +79,7 @@ elif [ "$ARCH" = "x86_64" ]; then
   CHOST="x86_64"
 fi
 
+### Preparing Source
 rm -rf $TMP
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
@@ -76,35 +89,25 @@ cd $DIR
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
-( mkdir -p build \
-    && cd build \
-      && cmake .. \
-    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
-    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DCMAKE_INSTALL_PREFIX=/usr \
-    -DSYSCONF_INSTALL_DIR=/etc \
-    -DMAN_INSTALL_DIR=/usr/man \
-    -DINCLUDE_INSTALL_DIR=/usr/include \
-    -DLIB_SUFFIX:STRING=${LIBDIRSUFFIX} \
-    -DLIB_INSTALL_DIR=/usr/lib${LIBDIRSUFFIX} \
-    -DRENDER_LIB=CAIRO \
-    -DBUILD_SHARED_LIBS:BOOL=ON \
-    && make $JOBS \
-&& make install DESTDIR=$PKG ) 
+# Customize as you need
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
+./configure \
+  --prefix=/usr \
+  --libdir=/usr/lib$LIBDIRSUFFIX \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --mandir=/usr/man \
+  --enable-static=no \
+  --enable-gsettings \
+  --docdir=/usr/doc/$PKGNAME-$VERSION \
+  --build=$CHOST-slackware-linux
+make $JOBS
+make install DESTDIR=$PKG
 
-# Installing desktop file menu and icons
-mkdir -p $PKG/usr/share/{applications,pixmaps}
-cat scribus.desktop > $PKG/usr/share/applications/scribus.desktop
-( cd $PKG/usr/share/pixmaps ; ln -s ../scribus/icons/scribus.png . )
-
+# Documentations
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION
 cp -r $DOCS $PKG/usr/doc/$PKGNAME-$VERSION
-
-# Fix doc and manpage directory
-mv $PKG/usr/share/man $PKG/usr
-cp -a $PKG/usr/share/doc/$PKGNAME/* $PKG/usr/doc/$PKGNAME-$VERSION
-rm -rf $PKG/usr/share/doc
  
 mkdir -p $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild
 cd $CWD
@@ -119,28 +122,16 @@ if [ -d $PKG/usr/man ]; then
     )
 fi
 
+# Strip binary files
 ( cd $PKG
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
   find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
 )
 
+
+# Preparing to packaging
 mkdir -p $PKG/install
-
-# Building some post-install execution script 	
-	echo "if [ -x /usr/bin/update-mime-database ]; then
-  /usr/bin/update-mime-database /usr/share/mime &> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/update-desktop-database ]; then
-  /usr/bin/update-desktop-database 1> /dev/null 2> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/gtk-update-icon-cache ]; then
-  /usr/bin/gtk-update-icon-cache  -f -q /usr/share/icons/hicolor 1> /dev/null 2> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-
 cat $CWD/slack-desc > $PKG/install/slack-desc
 [ -e $CWD/doinst.sh ] && cat $CWD/doinst.sh > $PKG/install/doinst.sh
 [ -e $CWD/doinst.sh.gz ] && zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
@@ -149,10 +140,11 @@ cd $PKG
 chown -R root:root $PKG
  
 if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
-  requiredbuilder -y -v -s $CWD $PKG
+  requiredbuilder -y -v -s $CWD $PKG   # add "-c -b" if you have binary files in /usr/share 
   [ -e install/slack-required ]&&cat install/slack-required > $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/slack-required
 fi
 
+# Packaging
 /sbin/makepkg -l y -c n $OUTPUT/$PKGNAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
  
 if [ "$1" = "--cleanup" ]; then
